In [1]:
import torch

In [2]:
x = torch.arange(14)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [4]:
x.shape

torch.Size([14])

In [5]:
x.numel()

14

In [6]:
X = x.reshape(2,7)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [11]:
X

tensor([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13]])

In [10]:
X = x.reshape(3,5)
X

RuntimeError: shape '[3, 5]' is invalid for input of size 14

In [12]:
torch.zeros((1,2,3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [13]:
torch.ones((1,2,3))

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [14]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2],[3,4],[5,6]]])

ValueError: expected sequence of length 3 at dim 2 (got 2)

In [19]:
torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,1],[3,4,1],[5,6,1]]])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 1],
         [3, 4, 1],
         [5, 6, 1]]])

In [24]:
torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,1],[3,4,1],[5,6,1]]]).shape

torch.Size([2, 3, 3])

In [25]:
# 元素运算
