In [1]:
import torch

In [2]:
x = torch.arange(14)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [4]:
x.shape

torch.Size([14])

In [5]:
x.numel()

14

In [6]:
X = x.reshape(2,7)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [11]:
X

tensor([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13]])

In [10]:
X = x.reshape(3,5)
X

RuntimeError: shape '[3, 5]' is invalid for input of size 14

In [12]:
torch.zeros((1,2,3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [13]:
torch.ones((1,2,3))

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [14]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2],[3,4],[5,6]]])

ValueError: expected sequence of length 3 at dim 2 (got 2)

In [19]:
torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,1],[3,4,1],[5,6,1]]])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 1],
         [3, 4, 1],
         [5, 6, 1]]])

In [24]:
torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,1],[3,4,1],[5,6,1]]]).shape

torch.Size([2, 3, 3])

In [3]:
import torch# 元素运算
x = torch.tensor([1.0,3,4,5])
y = torch.tensor([2,3,3,2])
x+y, x-y, x*y, x/y, x**y

(tensor([3., 6., 7., 7.]),
 tensor([-1.,  0.,  1.,  3.]),
 tensor([ 2.,  9., 12., 10.]),
 tensor([0.5000, 1.0000, 1.3333, 2.5000]),
 tensor([ 1., 27., 64., 25.]))

In [6]:
# 把多个张量连结在一起
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.3,1,3,5], [1,2,3,4], [4,3,2,1]])
torch.cat((X,Y), dim=0),torch.cat((X,Y), dim=1)

(tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000],
         [ 2.3000,  1.0000,  3.0000,  5.0000],
         [ 1.0000,  2.0000,  3.0000,  4.0000],
         [ 4.0000,  3.0000,  2.0000,  1.0000]]),
 tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  2.3000,  1.0000,  3.0000,  5.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000,  1.0000,  2.0000,  3.0000,  4.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000,  4.0000,  3.0000,  2.0000,  1.0000]]))

In [8]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
Y

tensor([[2.3000, 1.0000, 3.0000, 5.0000],
        [1.0000, 2.0000, 3.0000, 4.0000],
        [4.0000, 3.0000, 2.0000, 1.0000]])

In [10]:
# 按元素值判别
X==Y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [12]:
# 广播机制，维度不同，矩阵相加，容易出错，
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [13]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [12]:
import torch
# 内存
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.3,1,3,5], [1,2,3,4], [4,3,2,1]])
before = id(Y)
Y = Y+X
id(Y) == before

False

In [13]:
Z = torch.zeros_like(Y)
print('id(Z): ',id(Z))
Z[:] = X+Y
print('id(Z): ',id(Z))

id(Z):  2008719534024
id(Z):  2008719534024


In [14]:
# 如果后续不用此个变量，用“+=”，不要用“=”，这样会减少操作的内存开销
before = id(X)
X += Y
id(X) == before

True

In [17]:
# 转换为NumPy张量
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [18]:
# 将大小为1的张量转换为Python标量
a = torch.tensor([3.14])
a, a.item(), float(a), int(a)

(tensor([3.1400]), 3.140000104904175, 3.140000104904175, 3)